name: Github Actions Demo

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
    inputs:
      environments:
        description: "where to deploy"
        required: true
        type: environment
  schedule:
    - cron: '15 6 * * 0'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
       - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

       - uses: actions/checkout@v4

       - name: List files in the repository
         run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
    
  Deploy:
    name: ${{ inputs.environment}}
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: echo "deploy this "
  
    
